version: "0.1"
services:
  alus-coherence-processor:
    build: .
    volumes:
      - /mnt/vol:/mnt/vol
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python3 processor.py --input-dir /mnt/vol/input --output-dir /mnt/vol/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
